### ISSUE TITLE
repo DonPAPI changed location of DonPAPI.py

### ISSUE THREAD

**Issue by TerickJojo** [lefayjey/linWinPwn#15]
`chmod: cannot access '/opt/lwp-scripts/DonPAPI-main/DonPAPI.py': No such file or directory`
![image](https://github.com/lefayjey/linWinPwn/assets/24235319/f939ea52-d7b3-4129-8928-3ec303b1f3ce)

**Comment by lefayjey** [comment]
Thanks! Fixed in 0.8.3

Now the `./install.sh` script installs DonPAPI using pipx instead of downloading the repo.
