### ISSUE TITLE
problem with --log

### ISSUE THREAD

**Issue by rout3rx** [lefayjey/linWinPwn#16]
hello
I think the switch --log was added in the new version of crackmapexec and it is not supported in the active version 5.4. Therefore, I am facing an error in the implementation of linwinpwn. How should I install Crackmapexec version 6 on Kali? it is not available in repository
thanks

**Comment by lefayjey** [comment]
Hello 

You can uninstall the crackmapexec version installed in Kali, and use pip or pipx to install the latest version directly

```
pip3 install --user pipx --upgrade
pipx ensurepath
pipx install git+https://github.com/mpgn/CrackMapExec.git --force
```

**Comment by lefayjey** [comment]
As crackmapexec has been replaced by NetExec, I will close this issue.
