### ISSUE TITLE
Request compatibility with Kali.

### ISSUE THREAD

**Issue by leebaird** [lefayjey/linWinPwn#2]
Some of the packages are already installed on Kali or could be installed via their repos.

**Comment by lefayjey** [comment]
Thank you for your comment. The tool is compatible with Kali but does not in fact use the default impacket and crackmapexec installations in Kali. 
I've updated the default variables in commit #e54ff86a24a46a407511c0b66fb8d972fc309d65 to use the default impacket and crackmapexec in Kali and updated the setup steps to cover both Kali and non-Kali machines
