### ISSUE TITLE
dc-host

### ISSUE THREAD

**Issue by sec13b** [lefayjey/linWinPwn#23]
bash linWinPwn.sh -t 10.70.8.100  -u user -p 'passwd123' --auto

![image](https://github.com/lefayjey/linWinPwn/assets/123419537/fa91caff-f07e-4337-9a2c-109b4113496c)

![image](https://github.com/lefayjey/linWinPwn/assets/123419537/5cffc82a-b328-4363-a9f9-1bc0ae970f38)

**Comment by lefayjey** [comment]
Hey!
You're using an older version of impacket that doesn't have the parameter `-dc-host`. Try again after updating impacket
Thanks

**Comment by lefayjey** [comment]
In the screenshot, the impacket version is v.0.9.24. The latest is v.0.11.0 (https://github.com/fortra/impacket)

**Comment by protrading104** [comment]
![image](https://github.com/lefayjey/linWinPwn/assets/71656833/b14b2db6-ac86-4758-a3bd-358a9407079f)

I get a similar error with version 11 of impacket. any ideas why ?

**Comment by lefayjey** [comment]
The parameter is present on their latest GitHub repo https://github.com/fortra/impacket/blob/master/examples/GetUserSPNs.py#L526

Try installing using `pip3 install git+https://github.com/fortra/impacket` or
`pipx install git+https://github.com/fortra/impacket`
