### ISSUE TITLE
Complete Menu

### ISSUE THREAD

**Issue by JxB1990** [lefayjey/linWinPwn#26]
Hello buddy, awesome tool you have created here,  congratz, i have a question, why i cant see the menu as you have the example on the git, if i dont use any tags its gives me only configuration or authentication, im missing somenthing? thanks in advance

**Comment by lefayjey** [comment]
Hey!
Thanks for the feedback, appreciate it.
You have to press Enter again. In the videos the Configuration and Authentication Menus weren't introduced yet.
