### ISSUE TITLE
Please ensure netexec is installed and try again... 

### ISSUE THREAD

**Issue by KreativeNerd** [lefayjey/linWinPwn#29]
I am getting "Please ensure netexec is installed and try again..." error. My netexec is running perfectly. I have check the paths and .zshrc file yet everything seems to be set correctly. All these are shown in the image below:
┌──(kali㉿Smart-Hacker)-[~]
└─$ echo $PATH
/home/kali/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/games:/usr/games:/home/kali/go/bin:/home/kali/.local/bin
                                                                                                                                              
┌──(kali㉿Smart-Hacker)-[~]
└─$ echo $SHELL  
/usr/bin/zsh

┌──(kali㉿Smart-Hacker)-[~]
└─$ nano .zshrc                                                                                                                                        
# Created by `pipx` on 2024-09-05 07:02:47. This is from .zshrc file
export PATH="$PATH:/home/kali/.local/bin"

┌──(kali㉿Smart-Hacker)-[~]
└─$ nano .bashrc
This is from .bashrc file. I added this one manually
export PATH=$PATH:/home/kali/.local/bin

What could now be the issue?
![image](https://github.com/user-attachments/assets/2668b305-7e66-4ae7-8b1c-5995ee427d01)

![image](https://github.com/user-attachments/assets/f44a610e-29b9-4bb3-b804-c98a1ee39898)

**Comment by lefayjey** [comment]
Hello

Can you try running linWinPwn without sudo? It's possible it's not finding netexec as it's installed under the context of the user Kali

Thanks
