### ISSUE TITLE
gMSA \ LdapRelayScan - verify the location

### ISSUE THREAD

**Issue by Bobby87654** [lefayjey/linWinPwn#3]
Hi !
How i can fix this trouble?

`
[*] gMSA Dump
[-] Please verify the location of gMSADumper.py

[*] LdapRelayScan checks
[-] Please verify the location of LdapRelayScan.py
`

**Comment by lefayjey** [comment]
Hello ! 

Did you try executing the `linWinPwn.sh` script from the linWinPwn folder ? 

If the error still occurs, you can also modify line 46 `scripts_dir="./Scripts"` to the full location of the scripts (for example `/opt/linWinPwn/Scripts`  or `/root/linWinPwn/Scripts`, depending on where you cloned the repo)

**Comment by Bobby87654** [comment]
It helped me to fix the error by changing the path on line 46 to full. Thanks
