### ISSUE TITLE
LinWinPwn Cannot handle spaces in username

### ISSUE THREAD

**Issue by Senne-s** [lefayjey/linWinPwn#34]
I noticed it was not possible to utilize a username containing spaces. Some companies use spaces in their AD usernames, so it would be nice if this would be added. Seems like an easy fix when taking a quick look at the code.
Thanks in Advance!

**Comment by lefayjey** [comment]
Hey, thanks for the note, this new commit should have fixed it: https://github.com/lefayjey/linWinPwn/commit/127b39c767fda3750c26a6c3c46e060bac08c10d

let me know if you have issues with it.
