### ISSUE TITLE
 "class": algorithms.Blowfish

### ISSUE THREAD

**Issue by gearcapitan** [lefayjey/linWinPwn#5]
Users Enumeration (Null session)                                                                   

/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

[+] Found 0 users using RPC User Enum
                                                                                                       
[*] Users Enumeration (Null session)                                                                   
/usr/lib/python3/dist-packages/paramiko/transport.py:236: CryptographyDeprecationWarning: Blowfish has been deprecated
  "class": algorithms.Blowfish,

![imagen](https://user-images.githubusercontent.com/13740942/203896742-cebad1e4-15c7-4d87-98ef-262f21bbc05f.png)

**Comment by lefayjey** [comment]
Issue unrelated to the tool. The warning is caused by an older version of paramiko: 
https://github.com/paramiko/paramiko/issues/2038

**Comment by SheepTAOCN** [comment]
Thanks very much. When I upgrade paramiko, the warning is gone.
