### ISSUE TITLE
No module named 'impacket.dcerpc.v5.rpch'

### ISSUE THREAD

**Issue by gearcapitan** [lefayjey/linWinPwn#6]
[*] ADCS Enumeration
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/spooler.py: No module named 'impacket.dcerpc.v5.rpch'
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/ldap-checker.py: No module named 'msldap.commons.factory'
SMB         10.1.11.53      445    MEX1DOMCTL01     [*] Windows Server 2016 Standard 14393 x64 (name:MEX1DOMCTL01) (domain:bentoint.com) (signing:True) (SMBv1:True)

[*] Users Description containing word: pass
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/spooler.py: No module named 'impacket.dcerpc.v5.rpch'
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/ldap-checker.py: No module named 'msldap.commons.factory'
SMB         10.1.11.53      445    MEX1DOMCTL01     [*] Windows Server 2016 Standard 14393 x64 (name:MEX1DOMCTL01) (domain:bentoint.com) (signing:True) (SMBv1:True)

[*] Get MachineAccountQuota
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/spooler.py: No module named 'impacket.dcerpc.v5.rpch'
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/ldap-checker.py: No module named 'msldap.commons.factory'
SMB         10.1.11.53      445    MEX1DOMCTL01     [*] Windows Server 2016 Standard 14393 x64 (name:MEX1DOMCTL01) (domain:bentoint.com) (signing:True) (SMBv1:True)
MAQ         10.1.11.53      389    MEX1DOMCTL01     [*] Getting the MachineAccountQuota

[*] LDAP-signing check
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/spooler.py: No module named 'impacket.dcerpc.v5.rpch'
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/ldap-checker.py: No module named 'msldap.commons.factory'
SMB         10.1.11.53      445    MEX1DOMCTL01     [*] Windows Server 2016 Standard 14393 x64 (name:MEX1DOMCTL01) (domain:bentoint.com) (signing:True) (SMBv1:True)
LDAP-SIG... 10.1.11.53      389    MEX1DOMCTL01     LDAP signing is NOT enforced on 10.1.11.53
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/spooler.py: No module named 'impacket.dcerpc.v5.rpch'
[-] Failed loading module at /usr/lib/python3/dist-packages/cme/modules/ldap-checker.py: No module named 'msldap.commons.factory'
[-] Module not found
![imagen](https://user-images.githubusercontent.com/13740942/203896955-bc12a4a3-882f-41ac-b4ab-f5788bc489fb.png)

**Comment by lefayjey** [comment]
The errors are related to missing python modules that crackmapexec and impacket are using. 
You need to check the installations of crackmapexec and impacket. You can use the script "install.sh"
